apiVersion: v1
data:
  auth-token: YXV0aF9tU2JBYkJlVTRaUDNBVFJ3QmJZbDhrbG8yNkREQlpISg==
kind: Secret
metadata:
  creationTimestamp: "2026-06-14T10:29:44Z"
  name: dash0-secret
  namespace: observability
  resourceVersion: "25725"
  uid: 3adb311b-5d75-48f1-912d-2bfbb89b6682
type: Opaque
