apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"postgres","namespace":"otel-lab"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"postgres"}},"serviceName":"postgres","template":{"metadata":{"labels":{"app":"postgres"}},"spec":{"containers":[{"env":[{"name":"POSTGRES_DB","value":"otellab"},{"name":"POSTGRES_USER","value":"otellab"},{"name":"POSTGRES_PASSWORD","value":"otellab"}],"image":"postgres:16-alpine","name":"postgres","ports":[{"containerPort":5432}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
    creationTimestamp: "2026-06-14T10:39:38Z"
    generation: 1
    name: postgres
    namespace: otel-lab
    resourceVersion: "27812"
    uid: d897d3d6-b20e-4692-b8f2-bab45f866e96
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: postgres
    serviceName: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
        - env:
          - name: POSTGRES_DB
            value: otellab
          - name: POSTGRES_USER
            value: otellab
          - name: POSTGRES_PASSWORD
            value: otellab
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          name: postgres
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: postgres-68b69896c
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: postgres-68b69896c
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
