apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: otel-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: postgres
            topologyKey: kubernetes.io/hostname
      containers:
        - name: gateway
          image: python:3.13.14-slim
          command: ["sh", "-c"]
          args:
            - pip install fastapi==0.115.12 "uvicorn[standard]==0.34.3" httpx==0.28.1 pydantic==2.11.4 structlog==25.3.0 --quiet && uvicorn main:app --host 0.0.0.0 --port 8000
          workingDir: /app
          volumeMounts:
            - name: app-code
              mountPath: /app
          env:
            - name: PRODUCT_SVC_URL
              value: "http://product-svc:8001"
            - name: LLM_SVC_URL
              value: "http://llm-svc:8002"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: app-code
          configMap:
            name: gateway-code
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: otel-lab
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8000
