apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: otel-lab
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: otellab
            - name: POSTGRES_USER
              value: otellab
            - name: POSTGRES_PASSWORD
              value: otellab
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: otel-lab
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
