apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc
  namespace: otel-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-svc
  template:
    metadata:
      labels:
        app: product-svc
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: postgres
            topologyKey: kubernetes.io/hostname
      containers:
        - name: product-svc
          image: python:3.13.14-slim
          command: ["sh", "-c"]
          args:
            - pip install fastapi==0.115.12 "uvicorn[standard]==0.34.3" psycopg2-binary==2.9.10 pydantic==2.11.4 structlog==25.3.0 opentelemetry-api==1.42.1 opentelemetry-sdk==1.42.1 opentelemetry-exporter-otlp-proto-grpc==1.42.1 opentelemetry-instrumentation-fastapi==0.63b1 opentelemetry-instrumentation-psycopg2==0.63b1 opentelemetry-semantic-conventions==0.63b1 --quiet && uvicorn main:app --host 0.0.0.0 --port 8001
          workingDir: /app
          volumeMounts:
            - name: app-code
              mountPath: /app
          env:
            - name: DATABASE_URL
              value: "postgresql://otellab:otellab@postgres:5432/otellab"
            - name: OTEL_SERVICE_NAME
              value: "product-svc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcol-opentelemetry-collector.observability.svc.cluster.local:4317"
          ports:
            - containerPort: 8001
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: app-code
          configMap:
            name: product-svc-code
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: otel-lab
spec:
  selector:
    app: product-svc
  ports:
    - port: 8001
      targetPort: 8001