config:
  data:
    attributes:
      kubernetes:
        cluster_name: otel-lab
        enable: true
    discovery:
      instrument:
      - k8s_namespace: otel-lab
    ebpf:
      enable_context_propagation: true
      traffic_control_backend: tcx
    network:
      cidrs:
      - cidr: 10.0.0.0/8
        name: cluster-internal
      - cidr: 0.0.0.0/0
        name: external
      enable: true
      reporting_period: 5s
    otel_metrics_export:
      endpoint: http://otelcol.observability.svc.cluster.local:4317
      interval: 5s
    otel_traces_export:
      endpoint: http://otelcol.observability.svc.cluster.local:4317
    routes:
      unmatched: heuristic
daemonset:
  enabled: true
dnsPolicy: ClusterFirstWithHostNet
hostNetwork: true
hostPID: true
image:
  pullPolicy: IfNotPresent
  repository: grafana/beyla
  tag: 3.20.0
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
    - BPF
    - SYS_PTRACE
    - NET_RAW
    - CHECKPOINT_RESTORE
    - DAC_READ_SEARCH
    - PERFMON
    - SYS_RESOURCE
    - SYS_ADMIN
    - NET_ADMIN
    drop:
    - ALL
  privileged: true
  readOnlyRootFilesystem: false
  runAsUser: 0
tolerations:
- effect: NoSchedule
  operator: Exists
- effect: NoExecute
  operator: Exists